# Generated by Django 4.2.1 on 2023-05-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('idEvento', models.IntegerField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField(null=True)),
                ('idTicket', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventosData',
            fields=[
                ('idEventoData', models.IntegerField(primary_key=True, serialize=False)),
                ('idEvento', models.IntegerField(null=True)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha', models.DateField(null=True)),
                ('foto', models.BinaryField(null=True)),
                ('categoria', models.CharField(max_length=20, null=True)),
                ('genero', models.CharField(max_length=20, null=True)),
                ('provincia', models.CharField(max_length=20, null=True)),
                ('localidad', models.CharField(max_length=20, null=True)),
                ('calle', models.CharField(max_length=30, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('rss', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('idPermiso', models.IntegerField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField(null=True)),
                ('restricciones', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField(null=True)),
                ('rol', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.IntegerField(primary_key=True, serialize=False)),
                ('idEvento', models.IntegerField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fechayhora', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('idUserData', models.IntegerField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
                ('nombres', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaNac', models.DateField()),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('idUserData', models.IntegerField(null=True)),
                ('idPermiso', models.IntegerField(null=True)),
                ('idRol', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
