# Generated by Django 4.2.1 on 2023-06-03 00:35

import DbEnterarte.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_permission', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
                ('restrictions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
                ('rol', models.CharField(max_length=15)),
                ('id_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.permissions')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingOrder',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateTime', models.DateTimeField()),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.events')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.roles')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id_user_data', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.userdata'),
        ),
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.events')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.shoppingorder')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=DbEnterarte.models.generate_random_min_value), django.core.validators.MaxValueValidator(25000000)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dateTime', models.DateTimeField()),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.events')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingorder',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.user'),
        ),
        migrations.AddField(
            model_name='roles',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.user'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.user'),
        ),
        migrations.CreateModel(
            name='EventsData',
            fields=[
                ('id_event_data', models.AutoField(primary_key=True, serialize=False, verbose_name=int)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('photo', models.ImageField(default=None, upload_to='Galeria')),
                ('category', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('socialNetworks', models.CharField(max_length=20)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.ticket', to_field='id_ticket'),
        ),
        migrations.AddField(
            model_name='events',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DbEnterarte.user'),
        ),
    ]
