# Generated by Django 4.2.1 on 2023-06-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterarteapp', '0002_remove_client_lastname_client_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterarteapp.article'),
        ),
    ]
